# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

init:
  - git config --global core.autocrlf input

cache:
  - C:\Users\appveyor\.node-gyp
  - '%AppData%\npm-cache'

# what combinations to test
environment:
  matrix:
    - nodejs_version: 6
    - nodejs_version: 4

install:
  - ps: Install-Product node $env:nodejs_version x64
  - npm -g install npm@latest
  - set PATH=%APPDATA%\npm;%PATH%
  - npm install --global electron@1.4.4
  - npm install

build: off

test_script:
  - node --version
  - npm --version
  - cmd: npm test
